"""CLI Runner and Interactive REPL for the Local OS Agent."""

import argparse
import logging
import sys
from typing import Any

from agent import OSAgent
from config import config
from schemas import AgentResponse, ToolAction, ToolExecutionResult
from tools import execute_tool, list_tools
from tools.steam import discover_installed_steam_games

# Ensure UTF-8 output on Windows consoles
if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("local_os_agent")


def print_banner() -> None:
    banner = r"""
  ___  ____       _                    _   
 / _ \/ ___|     / \   __ _  ___ _ __ | |_ 
| | | \___ \    / _ \ / _` |/ _ \ '_ \| __|
| |_| |___) |  / ___ \ (_| |  __/ | | | |_ 
 \___/|____/  /_/   \_\__, |\___|_| |_|\__|
                      |___/                
==================================================
 Local OS Agent - Production LLM Desktop Controller
==================================================
"""
    print(banner)


def check_llm_connection(agent: OSAgent) -> bool:
    """Verifies that the configured local LLM endpoint is reachable."""
    try:
        models_resp = agent.client.models.list()
        available = [m.id for m in models_resp.data] if hasattr(models_resp, "data") else []
        print(f"[+] Successfully connected to LLM at {agent.base_url}")
        if available:
            print(f"    Available models: {', '.join(available[:5])}")
        return True
    except Exception as e:
        print(f"[!] Warning: Could not connect to local LLM at {agent.base_url}: {e}")
        print("    Ensure Ollama ('ollama run llama3.2') or LM Studio local server is active.")
        return False


def run_diagnostic() -> None:
    """Run non-destructive hardware and toolset diagnostic."""
    print("\n--- Running Local OS Agent Diagnostic ---")

    print("\n1. Registered Tools:")
    tools = list_tools()
    for name, tool_def in tools.items():
        sens = " [SENSITIVE - REQUIRES CONFIRMATION]" if tool_def.sensitive else ""
        print(f"  * {name}: {tool_def.description}{sens}")

    print("\n2. Steam Discovery Check:")
    try:
        games = discover_installed_steam_games()
        if games:
            print(f"  [+] Discovered {len(games)} installed Steam game(s):")
            for name, appid in list(games.items())[:8]:
                print(f"      - {name} (AppID: {appid})")
            if len(games) > 8:
                print(f"      ... and {len(games) - 8} more.")
        else:
            print("  [i] No Steam installation or games discovered.")
    except Exception as e:
        print(f"  [!] Steam discovery error: {e}")

    print("\n3. System Stats Test:")
    try:
        res = execute_tool("get_system_stats")
        print(f"  [+] Stats: {res.data}")
    except Exception as e:
        print(f"  [!] Stats error: {e}")

    print("\n4. Screenshot Test:")
    try:
        res = execute_tool("take_screenshot", {"filename": "diagnostic_test.png"})
        print(f"  [+] Screenshot: {res.message}")
    except Exception as e:
        print(f"  [!] Screenshot error: {e}")

    print("\n--- Diagnostic Finished ---\n")


def execute_and_display(agent: OSAgent, prompt: str) -> None:
    """Run a prompt through the agent and format execution results."""
    print(f"\n[User Query]: {prompt}")
    print("Thinking...")

    try:
        plan = agent.query_llm(prompt)
        print(f"\n[Agent Thought]: {plan.thought}")

        if not plan.actions:
            print("[i] No actions generated by the model.")
            return

        print(f"[Actions to Execute]: {len(plan.actions)}")
        for idx, action in enumerate(plan.actions, 1):
            args_str = ", ".join(f"{k}={v!r}" for k, v in action.args.items())
            print(f"  {idx}. {action.tool}({args_str})")

        print("\n[Execution Progress]:")

        def on_start(a: ToolAction):
            print(f"  -> Running {a.tool}...", end="", flush=True)

        def on_finish(r: ToolExecutionResult):
            icon = "+" if r.success else ("!" if r.status == "cancelled" else "x")
            print(f" [{icon}] Status: {r.status} - {r.message}")

        agent.execute_plan(plan, on_action_start=on_start, on_action_finish=on_finish)
        print("\nAll actions completed.")
    except Exception as e:
        print(f"\n[!] Error during agent run: {e}")


def interactive_voice_loop(agent: OSAgent) -> None:
    """Continuous voice-controlled loop listening for 'Cortana' and executing commands."""
    from voice import VoiceListener, extract_wake_word_command, speak

    print_banner()
    check_llm_connection(agent)
    print("\n" + "=" * 60)
    print("      🎙️  CORTANA VOICE INTERACTION MODE ACTIVATED  🎙️")
    print(f"      Wake Word : '{config.wake_word.upper()}' (e.g. 'Hey Cortana...')")
    print("      Persona   : Cortana (Elegant British Voice)")
    print("      Say 'exit', 'quit', or 'stop' to return to prompt.")
    print("=" * 60 + "\n")

    speak("Good day. I am Cortana. I will be listening for whenever you call my name.")
    listener = VoiceListener()
    listener.calibrate_ambient_noise(duration=0.8)

    while True:
        try:
            print(f"\n[🎙️ Listening for '{config.wake_word.title()}'...]")

            def on_speech():
                print("  -> Voice detected, recording...", end="", flush=True)

            text = listener.listen_command(
                timeout=10.0,
                on_speech_detected=on_speech,
            )

            if not text:
                continue

            # Check if Cortana was explicitly called
            is_called, command = extract_wake_word_command(text, wake_word=config.wake_word)

            if not is_called and config.require_wake_word:
                # Ambient noise or conversation not directed to Cortana
                print(f" (Ignored: '{text}' - '{config.wake_word.title()}' was not called)")
                continue

            # Use the remaining command or full text if wake word check was passed
            command_to_run = command if is_called else text
            print(f"\n[Cortana Called]: \"{text}\"")

            # Check for exit commands
            if any(w in text.lower() for w in ["exit", "quit", "goodbye", "stop voice", "shut down voice"]):
                print("Exiting Cortana voice mode.")
                speak("Goodbye for now.")
                break

            # If the user just called her name with no command ("Hey Cortana")
            if not command_to_run.strip():
                speak("Yes? I am listening.")
                print("  -> Cortana: 'Yes? I am listening.'")
                print("  -> Awaiting command...")
                followup = listener.listen_command(timeout=8.0)
                if followup:
                    print(f"\n[Command]: \"{followup}\"")
                    command_to_run = followup
                else:
                    speak("I did not catch that.")
                    continue

            execute_and_display(agent, command_to_run)

        except (KeyboardInterrupt, EOFError):
            print("\nExiting voice mode.")
            speak("Cortana standing down.")
            break


def interactive_repl(agent: OSAgent) -> None:
    """Runs interactive command REPL loop."""
    print_banner()
    check_llm_connection(agent)
    print("\nType your request or type 'voice' to speak. Type 'exit', 'quit', or 'diag'.\n")

    while True:
        try:
            user_input = input("Agent> ").strip()
            if not user_input:
                continue
            if user_input.lower() in ("exit", "quit", "q"):
                print("Exiting Local OS Agent. Goodbye!")
                break
            if user_input.lower() in ("diag", "diagnostic", "test"):
                run_diagnostic()
                continue
            if user_input.lower() in ("voice", "listen", "mic"):
                interactive_voice_loop(agent)
                continue

            execute_and_display(agent, user_input)
            print("-" * 50)
        except (KeyboardInterrupt, EOFError):
            print("\nExiting Local OS Agent. Goodbye!")
            break


def preview_all_voices() -> None:
    """Plays a preview of all available voices so the user can select their favorite."""
    from voice.tts import VOICE_PRESETS, TextToSpeech
    print("\n--- Auditioning Available Cortana Voices ---")
    for key, (voice_id, desc) in VOICE_PRESETS.items():
        print(f"\n[*] Voice Preset: '{key}' ({voice_id})")
        print(f"    Description : {desc}")
        print(f"    Speaking sample now...")
        engine = TextToSpeech(voice=voice_id)
        phrase = f"Hello. I am Cortana, using the {key} voice profile. How do I sound to you?"
        engine.speak(phrase, wait=True)
    print("\n--- Finished Auditioning Voices ---")
    print("Tip: You can select any voice permanently by launching with: --voice-name <name>")


def main() -> None:
    parser = argparse.ArgumentParser(description="Local OS Agent CLI")
    parser.add_argument("--prompt", "-p", type=str, help="Single prompt execution mode")
    parser.add_argument("--base-url", type=str, default=config.llm_base_url, help="LLM base URL")
    parser.add_argument("--model", "-m", type=str, default=config.llm_model, help="LLM model name")
    parser.add_argument("--voice", "-v", action="store_true", help="Launch directly in voice interaction mode")
    parser.add_argument("--voice-name", type=str, default=None, help="TTS Voice preset or full name (libby, aria, ava, maisie)")
    parser.add_argument("--preview-voices", action="store_true", help="Audition all available voice presets out loud")
    parser.add_argument("--no-tts", action="store_true", help="Disable voice speech feedback")
    parser.add_argument("--test-tools", action="store_true", help="Run local tool diagnostics")
    parser.add_argument("--debug", action="store_true", help="Enable debug logging")

    args = parser.parse_args()

    if args.debug:
        logging.getLogger().setLevel(logging.DEBUG)

    if args.preview_voices:
        preview_all_voices()
        return

    if args.voice_name:
        from voice.tts import VOICE_PRESETS, tts_engine
        selected = VOICE_PRESETS.get(args.voice_name.lower(), (args.voice_name, ""))[0]
        config.tts_voice = selected
        tts_engine.voice = selected

    if args.test_tools:
        run_diagnostic()
        return

    enable_voice = not args.no_tts
    agent = OSAgent(base_url=args.base_url, model=args.model, enable_voice=enable_voice)

    if args.voice:
        interactive_voice_loop(agent)
    elif args.prompt:
        execute_and_display(agent, args.prompt)
    else:
        interactive_repl(agent)


if __name__ == "__main__":
    main()
